[project]
name = "url-context-tool-sample"
version = "0.1.0"
description = "Simple example demonstrating how to use the Google url_context tool."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.33.0",
]
